development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: smbs_development
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: smbs_test
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: smbs_production
  pool: 5
  username: root
  password: 
  socket: /opt/local/var/run/mysql5/mysqld.sock
