#!/usr/bin/env ruby
File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

if ARGV[0]
  puts "\n\n\n---------------------------- \033[1;37;41m CACHE is OFF \033[0m ----------------------------\n\n\n"
else
  puts "\n\n\n--------------------------- \033[1;37;42m CACHE is ON \033[0m ---------------------------"
  puts " Try to use \033[1;31;40m./script/unicorn off\033[0m - to start server \033[1;31;40mWITHOUT\033[0m Cache"
  puts "---------------------------------------------------------------------\n\n\n"
  ENV['CACHE'] = 'CLASSES'
end

puts '=> Load Unicorn with settings:'
system "cat config/unicorn.development.rb"

puts "=> Start SMBS application"
puts "=> Ctrl-C to shutdown server"

puts cmd = 'unicorn_rails --env development --config-file config/unicorn.development.rb'
system cmd

trap(:INT) { exit }

system "[ -f tmp/pids/unicorn.pid ] && kill -s QUIT $(cat tmp/pids/unicorn.pid)"
puts "Exiting"